version: 5.0.0
variant: default
#variant: cyberpunk #赛博朋克风格
logo: /img/logo.svg
head:
    favicon: /img/logo.svg
    manifest:
        name:
        short_name:
        start_url:
        theme_color:
        background_color:
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type:
    open_graph:
        title:
        type: blog
        url:
        image:
        site_name:
        author: wanghuan
        description:
        twitter_card:
        twitter_id:
        twitter_site:
        google_plus:
        fb_admins:
        fb_app_id:
    structured_data:
        title:
        description:
        url:
        author:
        publisher:
        publisher_logo:
        image:
    meta:
        - ''
    rss:
navbar:
    menu:
        首页: /
        归档: /archives
        目录: /categories
        标签: /tags
        关于: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/IHuan123
#底部
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/IHuan123

# 文章显示设置
article:
    # Code highlight theme
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    #代码主题atom-one-light亮色，atom-one-dark暗色
    highlight:
        theme: atom-one-dark
        #theme: xt256 #赛博朋克风格
        clipboard: true
        fold: unfolded
    update_time: true
    thumbnail: true
    # 是否显示估算阅读时间
    readtime: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
##搜索
search:
    type: insight
##评论
comment:
#    type: disqus
    type: gitalk
    language: zh-CN #zh-CN #Localization language key, en, zh-CN and zh-TW are currently available.
    owner: IHuan123         # (required) GitHub user name
    repo: blog    # (required) GitHub repository name
    client_id: 67c282af028dafe35991     # (required) OAuth application client id
    client_secret: c97915ab7ba1661603bf54146da66c41b8124014 # (required) OAuth application client secret
    admin: ['IHuan123']
    create_issue_manually: true
    distraction_free_mode: false
    has_hot_recommend: true # 是否有热门推荐
    has_latest_comment: true #是否有最新评论
# 打赏功能
# http://ppoffice.github.io/hexo-theme-icarus/categories/Donation/
#donates:
#    -
#        type: afdian
#        url: ''
#    -
#        type: alipay
#        qrcode: ''
#    -
#        type: buymeacoffee
#        url: ''
#    -
#        type: patreon
#        url: ''
#    -
#        type: paypal
#        business: ''
#        currency_code: USD
#    -
#        type: wechat
#        qrcode: ''
#share:
#    type: sharethis
#    install_url: ''
sidebar:
    left:
        sticky: false
    right:
        sticky: true
widgets:
    #左边个人信息配置
    -
        # 部件位置（左）
        position: left
        # 个人信息
        type: profile
        # 作者名（字符串）
        author: wanghuan
        # 作者身份描述（字符串）
        author_title: super_huan@outlook.com
        # 作者当前居住地
        location: 成都
        # 头像（可用本地图片或网络图片链接）
        avatar: https://avatars.githubusercontent.com/u/42716044?s=40&v=4
        avatar_rounded: false
        gravatar:
        # 关注我的链接，可设为你的GitHub主页
        follow_link: https://github.com/IHuan123
         # 个人介绍部件底部图标社交链接
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/IHuan123
#            Facebook:
#                icon: fab fa-facebook
#                url: https://facebook.com
#            Twitter:
#                icon: fab fa-twitter
#                url: https://twitter.com
#            Dribbble:
#                icon: fab fa-dribbble
#                url: https://dribbble.com
#            RSS:
#                icon: fas fa-rss
#                url: /
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
#    -
#        position: left
#        type: links
#        links:
#            Hexo: https://hexo.io
#            Bulma: https://bulma.io
    -
        position: right
        type: categories
    -
        position: right
        type: recent_posts
    -
        position: right
        type: archives
    -
        position: right
        type: tags
#    -
#        position: left
#        type: subscribe_email
#        description:
#        feedburner_id: ''
#    -
#        position: left
#        type: adsense
#        client_id: ''
#        slot_id: ''
#    -
#        position: left
#        type: followit
#        description:
#        action_url: ''
#        verification_code: ''
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id:
    bing_webmaster:
        tracking_id:
    busuanzi: true
    cnzz:
        id:
        web_id:
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id:
    hotjar:
        site_id:
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project:
        security:
    twitter_conversion_tracking:
        pixel_id:
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome